// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7K0UvKtgUuDrmvsWG81VaWn052jAOaE',
    appId: '1:683178360201:web:b1e04b892b949c598ef558',
    messagingSenderId: '683178360201',
    projectId: 'venda-mais-83ea9',
    authDomain: 'venda-mais-83ea9.firebaseapp.com',
    storageBucket: 'venda-mais-83ea9.appspot.com',
    measurementId: 'G-P0Q1B7T2EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCr-pi1btrQggAymYp9bxe5b_zqkgItY',
    appId: '1:683178360201:android:1f09543daa4f6ed68ef558',
    messagingSenderId: '683178360201',
    projectId: 'venda-mais-83ea9',
    storageBucket: 'venda-mais-83ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58rS0y6QZQ7g5UW5sKZFdzd37da0DF58',
    appId: '1:683178360201:ios:13cc2b699cc23a578ef558',
    messagingSenderId: '683178360201',
    projectId: 'venda-mais-83ea9',
    storageBucket: 'venda-mais-83ea9.appspot.com',
    iosBundleId: 'com.example.vendamais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58rS0y6QZQ7g5UW5sKZFdzd37da0DF58',
    appId: '1:683178360201:ios:13cc2b699cc23a578ef558',
    messagingSenderId: '683178360201',
    projectId: 'venda-mais-83ea9',
    storageBucket: 'venda-mais-83ea9.appspot.com',
    iosBundleId: 'com.example.vendamais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7K0UvKtgUuDrmvsWG81VaWn052jAOaE',
    appId: '1:683178360201:web:6a096b28215af46e8ef558',
    messagingSenderId: '683178360201',
    projectId: 'venda-mais-83ea9',
    authDomain: 'venda-mais-83ea9.firebaseapp.com',
    storageBucket: 'venda-mais-83ea9.appspot.com',
    measurementId: 'G-V6X9PMSE00',
  );

}